[project]
name = "dancetime"
version = "0.1.0"
description = "A website to find dance events in Vienna."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4",
    "dateparser",
    "icalendar",
    "jinja2",
    "regex",
    "requests",
]
