worker_processes auto;
pid /run/nginx.pid;
error_log /dev/stderr warn;

events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;
    server_tokens off;
    sendfile on;

    server {
        listen 5000 default_server;
        listen [::]:5000 default_server;
        root /app/dist;
        index index.html;
    }
}
